export { Home } from "./Home/Home"
export { SingleHotel } from "./SinglehOTEL/SingleHotel"
export {SearchResults}from "./SearchResultPsge/SearchResultPage"
export { Wishlist } from "./Wishlist/wishlist"
export {Payment} from "./Payment/payment"