export  {getHotelsByPrice} from "./price-range"
export  {getHotelsByRoomsAndBeds} from "./rooms-beds"
export  {getHotelsByPropertyType } from "./property"
export  { getHotelsByRatings } from "./rating"  
export { getHotelsByCancelation} from "./hotel-cancel"
export {validateName} from "./name-regex"
export {validateEmail}from "./email-regex"
export {validatePassword} from "./password-regex"
export {validateNumber} from "./PhoneNumber-regex"
export {findhotelWishlist} from "./findhotel-wishlist"